language: erlang
otp_release:
  - R16B03
  - 17.5
  - 18.3
  - 19.1
script: curl -O -L https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && ./rebar3 update && ./rebar3 ct && ./rebar3 dialyzer
